/*
Deployment script for Test

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "aspnet-BookStore-20140221141131"
:setvar DefaultFilePrefix "aspnet-BookStore-20140221141131"
:setvar DefaultDataPath "C:\Users\jandresv\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"
:setvar DefaultLogPath "C:\Users\jandresv\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[Books]...';


GO
CREATE TABLE [dbo].[Books] (
    [Id]          INT             IDENTITY (1, 1) NOT NULL,
    [Title]       NVARCHAR (MAX)  NULL,
    [Author]      NVARCHAR (MAX)  NULL,
    [ISBN]        NVARCHAR (MAX)  NULL,
    [Publisher]   NVARCHAR (MAX)  NULL,
    [PublishYear] NVARCHAR (MAX)  NULL,
    [Summary]     NVARCHAR (MAX)  NULL,
    [PathImage]   NVARCHAR (MAX)  NULL,
    [Price]       DECIMAL (18, 2) NOT NULL,
    [Quantity]    INT             NOT NULL,
    CONSTRAINT [PK_dbo.Book] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Carts]...';


GO
CREATE TABLE [dbo].[Carts] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [CartId]      NVARCHAR (MAX) NULL,
    [BookId]      INT            NOT NULL,
    [Count]       INT            NOT NULL,
    [DateCreated] DATETIME       NOT NULL,
    CONSTRAINT [PK_dbo.Cart] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Carts].[IX_BookId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BookId]
    ON [dbo].[Carts]([BookId] ASC);


GO
PRINT N'Creating [dbo].[OrderDetails]...';


GO
CREATE TABLE [dbo].[OrderDetails] (
    [Id]        INT             IDENTITY (1, 1) NOT NULL,
    [OrderId]   INT             NOT NULL,
    [BookId]    INT             NOT NULL,
    [Quantity]  INT             NOT NULL,
    [UnitPrice] DECIMAL (18, 2) NOT NULL,
    CONSTRAINT [PK_dbo.OrderDetail] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[OrderDetails].[IX_Book_Id]...';


GO
CREATE NONCLUSTERED INDEX [IX_Book_Id]
    ON [dbo].[OrderDetails]([BookId] ASC);


GO
PRINT N'Creating [dbo].[OrderDetails].[IX_OrderId]...';


GO
CREATE NONCLUSTERED INDEX [IX_OrderId]
    ON [dbo].[OrderDetails]([OrderId] ASC);


GO
PRINT N'Creating [dbo].[Orders]...';


GO
CREATE TABLE [dbo].[Orders] (
    [Id]          INT             IDENTITY (1, 1) NOT NULL,
    [OrderDate]   DATETIME        NOT NULL,
    [UserName]    NVARCHAR (MAX)  NULL,
    [FirstName]   NVARCHAR (160)  NOT NULL,
    [LastName]    NVARCHAR (160)  NOT NULL,
    [Address]     NVARCHAR (70)   NOT NULL,
    [Town]        NVARCHAR (40)   NOT NULL,
    [Province]    NVARCHAR (40)   NOT NULL,
    [PostalCode]  NVARCHAR (10)   NOT NULL,
    [Country]     NVARCHAR (40)   NOT NULL,
    [PhoneNumber] NVARCHAR (24)   NOT NULL,
    [Email]       NVARCHAR (MAX)  NOT NULL,
    [Total]       DECIMAL (18, 2) NOT NULL,
    CONSTRAINT [PK_dbo.Order] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[UserProfile]...';


GO
CREATE TABLE [dbo].[UserProfile] (
    [UserId]      INT            IDENTITY (1, 1) NOT NULL,
    [UserName]    NVARCHAR (MAX) NULL,
    [Adress]      NVARCHAR (MAX) NULL,
    [Town]        NVARCHAR (MAX) NULL,
    [Province]    NVARCHAR (MAX) NULL,
    [Country]     NVARCHAR (MAX) NULL,
    [FirstName]   NVARCHAR (MAX) NULL,
    [LastName]    NVARCHAR (MAX) NULL,
    [EmailAdress] NVARCHAR (MAX) NULL,
    [PhoneNumber] NVARCHAR (MAX) NULL,
    [PostalCode]  NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC)
);


GO
PRINT N'Creating [dbo].[webpages_Membership]...';


GO
CREATE TABLE [dbo].[webpages_Membership] (
    [UserId]                                  INT            NOT NULL,
    [CreateDate]                              DATETIME       NULL,
    [ConfirmationToken]                       NVARCHAR (128) NULL,
    [IsConfirmed]                             BIT            NULL,
    [LastPasswordFailureDate]                 DATETIME       NULL,
    [PasswordFailuresSinceLastSuccess]        INT            NOT NULL,
    [Password]                                NVARCHAR (128) NOT NULL,
    [PasswordChangedDate]                     DATETIME       NULL,
    [PasswordSalt]                            NVARCHAR (128) NOT NULL,
    [PasswordVerificationToken]               NVARCHAR (128) NULL,
    [PasswordVerificationTokenExpirationDate] DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC)
);


GO
PRINT N'Creating [dbo].[webpages_OAuthMembership]...';


GO
CREATE TABLE [dbo].[webpages_OAuthMembership] (
    [Provider]       NVARCHAR (30)  NOT NULL,
    [ProviderUserId] NVARCHAR (100) NOT NULL,
    [UserId]         INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([Provider] ASC, [ProviderUserId] ASC)
);


GO
PRINT N'Creating [dbo].[webpages_Roles]...';


GO
CREATE TABLE [dbo].[webpages_Roles] (
    [RoleId]   INT            IDENTITY (1, 1) NOT NULL,
    [RoleName] NVARCHAR (256) NOT NULL,
    PRIMARY KEY CLUSTERED ([RoleId] ASC),
    UNIQUE NONCLUSTERED ([RoleName] ASC)
);


GO
PRINT N'Creating [dbo].[webpages_UsersInRoles]...';


GO
CREATE TABLE [dbo].[webpages_UsersInRoles] (
    [UserId] INT NOT NULL,
    [RoleId] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
);


GO
PRINT N'Creating DF__webpages___IsCon__145C0A3F...';


GO
ALTER TABLE [dbo].[webpages_Membership]
    ADD DEFAULT ((0)) FOR [IsConfirmed];


GO
PRINT N'Creating DF__webpages___Passw__15502E78...';


GO
ALTER TABLE [dbo].[webpages_Membership]
    ADD DEFAULT ((0)) FOR [PasswordFailuresSinceLastSuccess];


GO
PRINT N'Creating FK_dbo.Cart_dbo.Book_BookId...';


GO
ALTER TABLE [dbo].[Carts] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Cart_dbo.Book_BookId] FOREIGN KEY ([BookId]) REFERENCES [dbo].[Books] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_dbo.OrderDetail_dbo.Order_OrderId...';


GO
ALTER TABLE [dbo].[OrderDetails] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.OrderDetail_dbo.Order_OrderId] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_OrderDetails_Books...';


GO
ALTER TABLE [dbo].[OrderDetails] WITH NOCHECK
    ADD CONSTRAINT [FK_OrderDetails_Books] FOREIGN KEY ([BookId]) REFERENCES [dbo].[Books] ([Id]);


GO
PRINT N'Creating fk_UserId...';


GO
ALTER TABLE [dbo].[webpages_UsersInRoles] WITH NOCHECK
    ADD CONSTRAINT [fk_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[UserProfile] ([UserId]);


GO
PRINT N'Creating fk_RoleId...';


GO
ALTER TABLE [dbo].[webpages_UsersInRoles] WITH NOCHECK
    ADD CONSTRAINT [fk_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[webpages_Roles] ([RoleId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Carts] WITH CHECK CHECK CONSTRAINT [FK_dbo.Cart_dbo.Book_BookId];

ALTER TABLE [dbo].[OrderDetails] WITH CHECK CHECK CONSTRAINT [FK_dbo.OrderDetail_dbo.Order_OrderId];

ALTER TABLE [dbo].[OrderDetails] WITH CHECK CHECK CONSTRAINT [FK_OrderDetails_Books];

ALTER TABLE [dbo].[webpages_UsersInRoles] WITH CHECK CHECK CONSTRAINT [fk_UserId];

ALTER TABLE [dbo].[webpages_UsersInRoles] WITH CHECK CHECK CONSTRAINT [fk_RoleId];


GO
PRINT N'Update complete.'
GO
